# Generated by Django 4.2.7 on 2025-06-19 08:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Unique district code', max_length=10, unique=True)),
                ('department', models.CharField(choices=[('fire', 'Fire Department'), ('police', 'Police Department'), ('medical', 'Medical Department')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('coordinates', models.CharField(blank=True, help_text='Latitude,Longitude', max_length=50)),
                ('manager', models.CharField(max_length=100)),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
                ('manager_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('description', models.TextField(blank=True)),
                ('coverage_area', models.TextField(blank=True, help_text='Description of coverage area')),
                ('population_served', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, help_text='ID of user who created this district', null=True)),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['department', 'name'],
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.CreateModel(
            name='DistrictResource',
            fields=[
                ('resource_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('equipment', 'Equipment'), ('personnel', 'Personnel'), ('facility', 'Facility')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='districts.district')),
            ],
            options={
                'db_table': 'district_resources',
                'ordering': ['district', 'resource_type', 'name'],
            },
        ),
    ]
