# Generated by Django 4.2.7 on 2025-06-19 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('building_fire', 'Building Fire'), ('wildfire', 'Wildfire'), ('gas_leak', 'Gas Leak'), ('explosion', 'Explosion'), ('hazmat_incident', 'Hazmat Incident'), ('robbery', 'Robbery'), ('assault', 'Assault'), ('traffic_violation', 'Traffic Violation'), ('domestic_dispute', 'Domestic Dispute'), ('suspicious_activity', 'Suspicious Activity'), ('heart_attack', 'Heart Attack'), ('traffic_accident', 'Traffic Accident'), ('overdose', 'Overdose'), ('fall_injury', 'Fall Injury'), ('allergic_reaction', 'Allergic Reaction')], max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('department', models.CharField(choices=[('fire', 'Fire Department'), ('police', 'Police Department'), ('medical', 'Medical Department')], max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.CharField(blank=True, max_length=50)),
                ('outcome', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
