services:
  - type: web
    name: my_guardian_plus
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn emergency_system.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: emergency_system.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: my-db
          property: connectionString

databases:
  - name: my-db
    plan: free
