// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBDyOt9WQ-2FL9t27-VHO_kgjigLygBek',
    appId: '1:268468611744:web:f7b0583240db60a10d77c5',
    messagingSenderId: '268468611744',
    projectId: 'guardian-16d00',
    authDomain: 'guardian-16d00.firebaseapp.com',
    storageBucket: 'guardian-16d00.firebasestorage.app',
    measurementId: 'G-N5NN8WM84M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPMYfvhokDUehAx5U6Nz3G4z44ykcendA',
    appId: '1:268468611744:android:840ea4946cf3655e0d77c5',
    messagingSenderId: '268468611744',
    projectId: 'guardian-16d00',
    storageBucket: 'guardian-16d00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuwPoxuH6oJFCFGWdbEhbCoPJO8mQ1clE',
    appId: '1:268468611744:ios:95301de3f99bcc550d77c5',
    messagingSenderId: '268468611744',
    projectId: 'guardian-16d00',
    storageBucket: 'guardian-16d00.firebasestorage.app',
    iosBundleId: 'com.example.my_guardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuwPoxuH6oJFCFGWdbEhbCoPJO8mQ1clE',
    appId: '1:268468611744:ios:95301de3f99bcc550d77c5',
    messagingSenderId: '268468611744',
    projectId: 'guardian-16d00',
    storageBucket: 'guardian-16d00.firebasestorage.app',
    iosBundleId: 'com.example.my_guardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBDyOt9WQ-2FL9t27-VHO_kgjigLygBek',
    appId: '1:268468611744:web:777022099f301e240d77c5',
    messagingSenderId: '268468611744',
    projectId: 'guardian-16d00',
    authDomain: 'guardian-16d00.firebaseapp.com',
    storageBucket: 'guardian-16d00.firebasestorage.app',
    measurementId: 'G-D6XWCV2HFP',
  );
}
